### ISSUE TITLE
parse arguments

### ISSUE THREAD

**Issue by ripoul** [Airthee/LightshotSniffer#6]
`getArgumentValue("--gui", "True").upper() in ["TRUE", "YES", "OK", "1"]`

quand un booléen est passé en argument d'un programme par Default il est égale à False. Donc dans ton cas on ne cherche pas le valeur qui vient après --gui puisqu'il s'agira d'un autre argument. Le simple fait de mettre --gui le set a  true. Va voir https://docs.python.org/2/howto/argparse.html.

**Comment by Airthee** [comment]
Merci
Note pour moi-même : https://docs.python.org/2/howto/argparse.html#introducing-optional-arguments
